server:
  port: 9002

spring:
  application:
    name: nacos-payment-provider
  cloud:
    nacos:
      discovery:
        server-addr: 42.192.179.218:1111
        # server-addr: localhost:8848

management:
  endpoints:
    web:
      exposure:
        include: '*'